[install]
cmds = ["apk add --no-cache supervisor"]

[build]
cmds = [
    "composer install && npm install && npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan storage:unlink || true && php artisan storage:link && chmod 777 -R storage/ && chmod 777 -R public/ && chmod 777 -R bootstrap/cache && php artisan optimize"
]

[start]
cmd = "supervisord -c /app/supervisord.conf"
